export enum Strings {
    COMPLETED_TODO_UPDATE = "COMPLETED_TODO_UPDATE",
    REACTIVATE_TODO_UPDATE = "REACTIVATE_TODO_UPDATE",
    TODO_DATA_UPDATE = "TODO_DATA_UPDATE",

    ACTIVATED_TODO_DELETE = "ACTIVATED_TODO_DELETE",
    COMPLETED_TODO_DELETE = "COMPLETED_TODO_DELETE",


    TODO_COMPLETION_UPDATE = "Task Completed Successfully",
    TODO_REACTIVATE_UPDATE = "Todo Re-activated Updated",

    COMPLETED_TODOS = "COMPLETED_TODOS",
    ACTIVE_TODOS = "ACTIVE_TODOS",

    REACT_APP_API_URL = "https://todo-backend-dd5d.onrender.com"
}